### ISSUE TITLE
I have install your extension but its not working

### ISSUE THREAD

**Issue by rajkinkhabwala** [malamalca/vscode-gdl-syntax-highlighter#1]
I did the things which you mentioned in the installation part but I am able to use it. I can't find gdl in the command palette. 

And also how to use it?? can you help me with a guide for your extension.

**Comment by malamalca** [comment]
This extension is intended for syntax highlighting of .gdl files. There are no palettes, shortcuts or snippets.
After you load the extension and open your file, gdl function names, comments, strings,... should be colored according to your 
VBCode settings.
